# Generated by Django 2.1.7 on 2019-04-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realestate',
            old_name='username',
            new_name='mortID',
        ),
        migrations.RenameField(
            model_name='realestate',
            old_name='password',
            new_name='name',
        ),
    ]
