# Generated by Django 2.1.7 on 2019-04-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='startDate',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
